### ISSUE TITLE
Hello skydevil88

### ISSUE THREAD

**Issue by sphere1001** [skydevil88/XboxDownload-EN#2]
Sorry for any incovenience.
I have downloaded your tool, and it seems to do it's job quite well.

Now here comes my question.
Can you in effect download Games for the Xbox Game Pass for PC with the tool 
without getting licensing errors ?

If yes ,could you please explain ?
If no, it is still a very cool tool and thank you.

**Comment by skydevil88** [comment]
You need to have Xbox Game Pass Member, or having buy this game.

**Comment by sphere1001** [comment]
ok thank you for clarification
