### ISSUE TITLE
Update games with pc

### ISSUE THREAD

**Issue by moeinovic** [skydevil88/XboxDownload-EN#3]
Hello dear friend, thank you for your useful tool. I have a question: is there a way for me to update games using a PC? In our country, the Xbox network is restricted, and updating games is very difficult.
 I mean, can I download the update package via PC and transfer it to the console?

**Comment by skydevil88** [comment]
Yes, you can download the update package via PC and transfer it to the console,  Its the same package, if you choose update, it only update the data you need, but you should make sure that you have already download a whole package.

**Comment by moeinovic** [comment]
That's great! What I mean is that to update a game on the computer, I don't want to download the whole package. If Fortnite releases an update that is 15 gigabytes, I want to download just that 15GB and not the entire game data. Is such a thing possible?

**Comment by skydevil88** [comment]
No, because we don't know which update data is needed from the package.
