### ISSUE TITLE
Links for removed games

### ISSUE THREAD

**Issue by Madmatoster** [skydevil88/XboxDownload-EN#4]
Hi!

Thank you for this app.

Is there a way to download games that are removed from store?

Ie, Splinter Cell 1 gets info, but no download link, and Forza Horizon 1, 2, 3 doesn't show up when I search it, but FH3 shows when I paste direct link

**Comment by skydevil88** [comment]
For those games have no download link, you should find the ProductID, after update authorization, this APP will show out
XboxOne and MS Store (PC) download link (not include XboxSeries),

Way of update authorization
1.Back to Service tab, Click "Enable HTTP(S) service" and "Speed up MS Store (PC)" , then press "Start" butten. 
2.Open Xbox app, select a game and click install, await the log show out download link then complete update authorization.

Splinter Cell 1: https://xbox.skydevil.xyz?C46H5R7GT7X9
Forza Horizon 3: https://xbox.skydevil.xyz?9NBLGGH1Z7TW

**Comment by Madmatoster** [comment]
Thank you! It works now
